name: Manually triggered workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'If run flow, input "run".'
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_HASHE: ${{ github.sha }}

jobs:
  say_hello:
    if: github.event.inputs.logLevel == 'run'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"