name: Manually triggered workflow

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_HASHE: ${{ github.sha }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"
          ehco "GITHUB_TOKEN = ${GITHUB_TOKEN}"
          ehco "GITHUB_HASHE = ${GITHUB_HASHE}"