name: Manually triggered workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Passwordを入力してください。'
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_HASHE: ${{ github.sha }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  say_hello:
    if: github.event.inputs.logLevel == ${PASSWORD}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello!"